runtime: python37

default_expiration: "1h"
  
instance_class: F2

inbound_services:
  - warmup

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

handlers:
  - url: /.*
    script: auto