runtime: python37
  
instance_class: F1

env_variables:
  DJANGO_SETTINGS_MODULE: "IizakaEmpire.settings"

entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2

handlers:
  - url: /.*
    script: auto