# Generated by Django 3.0.5 on 2020-04-13 14:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0006_auto_20200410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=markdownx.models.MarkdownxField(help_text='box9 is note box<div>', verbose_name='Contents'),
        ),
    ]
