# Generated by Django 3.0.5 on 2020-04-15 03:24

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0007_auto_20200413_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', markdownx.models.MarkdownxField(help_text='This Field define SitePolicy', verbose_name='POLICY')),
            ],
        ),
    ]
