# Generated by Django 3.0.5 on 2020-04-22 12:43

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0008_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=markdownx.models.MarkdownxField(help_text='box9 is note box<div>\n outline is list\n <ul class="outline"><li><h4></h4></li></ul>', verbose_name='Contents'),
        ),
    ]
