# Generated by Django 3.1.2 on 2020-11-01 08:21

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0009_auto_20200422_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contents',
            field=markdownx.models.MarkdownxField(help_text='box9 is note box<div>\n outline is list <ul class="outline"><li><h4></h4></li></ul>', verbose_name='Contents'),
        ),
    ]
