# Generated by Django 3.1.2 on 2020-11-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0010_auto_20201101_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('slug', models.SlugField(max_length=16, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.kinds'),
        ),
    ]
