# Generated by Django 3.1.2 on 2021-01-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0011_auto_20201129_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_date',
            field=models.DateField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
